# Tibber Prices REST-Sensor
- platform: rest
  name: "Tibber Prices"
  resource: "https://api.tibber.com/v1-beta/gql"
  method: POST
  payload: '{ "query": "{ viewer { homes { currentSubscription { status priceInfo { current { total } today { total } tomorrow { total } } } } } }" }'
  json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
  json_attributes:
    - today
    - tomorrow
  value_template: "{{ value_json.data.viewer.homes[0].currentSubscription.priceInfo.current.total | float }}"
  scan_interval: 30
  headers:
    Authorization: "P4uayyO5YHJOTPdZk5BGCHcACDOylwlH3R8y1xVMn28"
    Content-Type: "application/json"
    User-Agent: "REST"
  unit_of_measurement: "EUR/kWh"

- platform: filter
  name: "smooth_scb_home_power"
  entity_id: sensor.scb_home_power
  filters:
    - filter: time_simple_moving_average
      window_size: "00:30"
